workflows:
  android-debug:
    name: Build Android APK
    max_build_duration: 120
    instance_type: linux_x2

    scripts:
      - name: Make Gradle executable
        script: chmod +x ./gradlew

      - name: Configure Android SDK
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build debug APK
        script: |
          ./gradlew clean assembleDebug

    artifacts:
      - "**/build/outputs/apk/debug/*.apk"
